CAMPAIGN_NAME=trinyvale \
FARRLIND_CAMPAIGN=trinyvale \
CAMPAIGN_DB=trinyvale \
CAMPAIGN_DB_PORT=5434 \
CAMPAIGN_WEB_PORT=8010 \
CAMPAIGN_ARCHIVE_PORT=8012 \
CAMPAIGN_ADMINER_PORT=8082 \
docker compose -p trinyvale up -d
