from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
WORKFLOW_PATH = REPO_ROOT / "workflows" / "session_workflow.yaml"
OUT_DIR = REPO_ROOT / "farrlind" / "out"

SESSION_RE = re.compile(r"^session0*(\d+)$", re.IGNORECASE)


def load_workflow_definition(path: Path = WORKFLOW_PATH) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def parse_session_number(session_ref: str | int) -> int:
    if isinstance(session_ref, int):
        if session_ref <= 0:
            raise ValueError("Session number must be positive.")
        return session_ref

    match = SESSION_RE.match(session_ref.strip())
    if match:
        return int(match.group(1))

    if session_ref.strip().isdigit():
        number = int(session_ref.strip())
        if number > 0:
            return number

    raise ValueError(f"Expected a session reference like session21, got {session_ref!r}.")


def session_name(session_ref: str | int) -> str:
    return f"session{parse_session_number(session_ref):02d}"


def workflow_state_schema_sql() -> str:
    return """
CREATE TABLE IF NOT EXISTS workflow_run (
    id                  SERIAL PRIMARY KEY,
    session_id          INT NOT NULL REFERENCES session(id),
    workflow_id         VARCHAR(120) NOT NULL,
    workflow_version    INT NOT NULL,
    workflow_name       TEXT,
    status              VARCHAR(30) NOT NULL DEFAULT 'initialized',
    initiated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    summary_comment     TEXT,
    metadata            JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE(session_id, workflow_id, workflow_version)
);

CREATE TABLE IF NOT EXISTS workflow_step_state (
    id                  SERIAL PRIMARY KEY,
    workflow_run_id     INT NOT NULL REFERENCES workflow_run(id) ON DELETE CASCADE,
    step_id             VARCHAR(120) NOT NULL,
    step_order          INT NOT NULL,
    display_name        TEXT NOT NULL,
    lane                VARCHAR(80),
    status              VARCHAR(30) NOT NULL DEFAULT 'pending',
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    summary_comment     TEXT,
    inputs              JSONB NOT NULL DEFAULT '[]'::jsonb,
    outputs             JSONB NOT NULL DEFAULT '[]'::jsonb,
    dependencies        JSONB NOT NULL DEFAULT '[]'::jsonb,
    gate                VARCHAR(80),
    rerun_policy        VARCHAR(80),
    canon_impact        VARCHAR(80),
    command             TEXT,
    status_rules        JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata            JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE(workflow_run_id, step_id)
);

CREATE INDEX IF NOT EXISTS idx_workflow_run_session
    ON workflow_run(session_id);
CREATE INDEX IF NOT EXISTS idx_workflow_run_identity
    ON workflow_run(workflow_id, workflow_version);
CREATE INDEX IF NOT EXISTS idx_workflow_run_status
    ON workflow_run(status);
CREATE INDEX IF NOT EXISTS idx_workflow_step_run_order
    ON workflow_step_state(workflow_run_id, step_order);
CREATE INDEX IF NOT EXISTS idx_workflow_step_status
    ON workflow_step_state(status);
""".strip()


def initialize_workflow_sql(
    session_ref: str | int,
    definition: dict[str, Any] | None = None,
) -> str:
    definition = definition or load_workflow_definition()
    workflow = definition["workflow"]
    steps = definition["steps"]
    name = session_name(session_ref)
    number = parse_session_number(session_ref)
    metadata = {
        "definition_format": workflow.get("definition_format"),
        "scope": workflow.get("scope"),
        "state_persistence": workflow.get("state_persistence"),
        "source_definition": str(WORKFLOW_PATH.relative_to(REPO_ROOT)),
    }

    statements = [
        "-- Generated by raglib.workflow_state. Safe to rerun.",
        "BEGIN;",
        workflow_state_schema_sql(),
        f"""
INSERT INTO session (session_number, title, notes)
VALUES ({number}, {sql_quote(f"Session {number:02d}")}, {sql_quote("Initialized by workflow state.")})
ON CONFLICT (session_number) DO NOTHING;
""".strip(),
        f"""
WITH upserted_workflow AS (
    INSERT INTO workflow_run (
        session_id, workflow_id, workflow_version, workflow_name, status, metadata
    )
    VALUES (
        (SELECT id FROM session WHERE session_number = {number}),
        {sql_quote(workflow["id"])},
        {int(workflow["version"])},
        {sql_quote(workflow.get("display_name"))},
        'initialized',
        {sql_json(metadata)}
    )
    ON CONFLICT (session_id, workflow_id, workflow_version)
    DO UPDATE SET
        workflow_name = EXCLUDED.workflow_name,
        metadata = workflow_run.metadata || EXCLUDED.metadata
    RETURNING id
)
{step_state_insert_sql(steps, name)}
""".strip(),
        "COMMIT;",
        "",
    ]
    return "\n\n".join(statements)


def step_state_insert_sql(steps: list[dict[str, Any]], name: str) -> str:
    rows = []
    for order, step in enumerate(steps, start=1):
        rows.append(
            "("
            f"{sql_quote(step['id'])}, "
            f"{order}, "
            f"{sql_quote(step['display_name'])}, "
            f"{sql_quote(step.get('lane'))}, "
            f"{sql_json(render_session_refs(step.get('expected_inputs', []), name))}, "
            f"{sql_json(render_session_refs(step.get('expected_outputs', []), name))}, "
            f"{sql_json(step.get('dependencies', []))}, "
            f"{sql_quote(step.get('gate'))}, "
            f"{sql_quote(step.get('rerun_policy'))}, "
            f"{sql_quote(step.get('canon_impact'))}, "
            f"{sql_quote(render_session_refs(step.get('command'), name))}, "
            f"{sql_json(render_session_refs(step.get('status_rules', {}), name))}, "
            f"{sql_json({'notes': step.get('notes'), 'dependency_mode': step.get('dependency_mode')})}"
            ")"
        )

    values = ",\n        ".join(rows)
    return f"""
INSERT INTO workflow_step_state (
    workflow_run_id, step_id, step_order, display_name, lane,
    inputs, outputs, dependencies, gate, rerun_policy, canon_impact,
    command, status_rules, metadata
)
SELECT
    upserted_workflow.id,
    step_values.step_id,
    step_values.step_order,
    step_values.display_name,
    step_values.lane,
    step_values.inputs,
    step_values.outputs,
    step_values.dependencies,
    step_values.gate,
    step_values.rerun_policy,
    step_values.canon_impact,
    step_values.command,
    step_values.status_rules,
    step_values.metadata
FROM upserted_workflow,
     (VALUES
        {values}
     ) AS step_values (
        step_id, step_order, display_name, lane,
        inputs, outputs, dependencies, gate, rerun_policy, canon_impact,
        command, status_rules, metadata
     )
ON CONFLICT (workflow_run_id, step_id)
DO UPDATE SET
    step_order = EXCLUDED.step_order,
    display_name = EXCLUDED.display_name,
    lane = EXCLUDED.lane,
    inputs = EXCLUDED.inputs,
    outputs = EXCLUDED.outputs,
    dependencies = EXCLUDED.dependencies,
    gate = EXCLUDED.gate,
    rerun_policy = EXCLUDED.rerun_policy,
    canon_impact = EXCLUDED.canon_impact,
    command = EXCLUDED.command,
    status_rules = EXCLUDED.status_rules,
    metadata = workflow_step_state.metadata || EXCLUDED.metadata;
""".strip()


def write_workflow_init_sql(session_ref: str | int, output_dir: Path = OUT_DIR) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    name = session_name(session_ref)
    output_path = output_dir / f"workflow_init_{name}.sql"
    output_path.write_text(initialize_workflow_sql(session_ref), encoding="utf-8")
    print(f"Wrote {output_path}")
    return output_path


def render_session_refs(value: Any, name: str) -> Any:
    if isinstance(value, str):
        return value.replace("sessionXX", name)
    if isinstance(value, list):
        return [render_session_refs(item, name) for item in value]
    if isinstance(value, dict):
        return {key: render_session_refs(item, name) for key, item in value.items()}
    return value


def sql_quote(value: Any) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def sql_json(value: Any) -> str:
    return f"{sql_quote(json.dumps(value, sort_keys=True))}::jsonb"
