from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path
from typing import Any
from datetime import datetime, timedelta, timezone

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
WORKFLOW_PATH = REPO_ROOT / "workflows" / "session_workflow.yaml"
OUT_DIR = REPO_ROOT / "farrlind" / "out"

SESSION_RE = re.compile(r"^session0*(\d+)$", re.IGNORECASE)


def load_workflow_definition(path: Path = WORKFLOW_PATH) -> dict[str, Any]:
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def parse_session_number(session_ref: str | int) -> int:
    if isinstance(session_ref, int):
        if session_ref < 0:
            raise ValueError("Session number cannot be negative.")
        return session_ref

    match = SESSION_RE.match(session_ref.strip())
    if match:
        return int(match.group(1))

    if session_ref.strip().isdigit():
        number = int(session_ref.strip())
        if number >= 0:
            return number

    raise ValueError(f"Expected a session reference like session21, got {session_ref!r}.")


def session_name(session_ref: str | int) -> str:
    return f"session{parse_session_number(session_ref):02d}"


def workflow_state_schema_sql() -> str:
    return """
CREATE TABLE IF NOT EXISTS workflow_run (
    id                  SERIAL PRIMARY KEY,
    session_id          INT NOT NULL REFERENCES session(id),
    workflow_id         VARCHAR(120) NOT NULL,
    workflow_version    INT NOT NULL,
    workflow_name       TEXT,
    status              VARCHAR(30) NOT NULL DEFAULT 'initialized',
    initiated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    summary_comment     TEXT,
    metadata            JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE(session_id, workflow_id, workflow_version)
);

CREATE TABLE IF NOT EXISTS workflow_step_state (
    id                  SERIAL PRIMARY KEY,
    workflow_run_id     INT NOT NULL REFERENCES workflow_run(id) ON DELETE CASCADE,
    step_id             VARCHAR(120) NOT NULL,
    step_order          INT NOT NULL,
    display_name        TEXT NOT NULL,
    lane                VARCHAR(80),
    status              VARCHAR(30) NOT NULL DEFAULT 'pending',
    started_at          TIMESTAMPTZ,
    completed_at        TIMESTAMPTZ,
    summary_comment     TEXT,
    inputs              JSONB NOT NULL DEFAULT '[]'::jsonb,
    outputs             JSONB NOT NULL DEFAULT '[]'::jsonb,
    dependencies        JSONB NOT NULL DEFAULT '[]'::jsonb,
    gate                VARCHAR(80),
    rerun_policy        VARCHAR(80),
    canon_impact        VARCHAR(80),
    command             TEXT,
    status_rules        JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata            JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE(workflow_run_id, step_id)
);

CREATE INDEX IF NOT EXISTS idx_workflow_run_session
    ON workflow_run(session_id);
CREATE INDEX IF NOT EXISTS idx_workflow_run_identity
    ON workflow_run(workflow_id, workflow_version);
CREATE INDEX IF NOT EXISTS idx_workflow_run_status
    ON workflow_run(status);
CREATE INDEX IF NOT EXISTS idx_workflow_step_run_order
    ON workflow_step_state(workflow_run_id, step_order);
CREATE INDEX IF NOT EXISTS idx_workflow_step_status
    ON workflow_step_state(status);
""".strip()


def initialize_workflow_sql(
    session_ref: str | int,
    definition: dict[str, Any] | None = None,
) -> str:
    definition = definition or load_workflow_definition()
    statements = [
        "-- Generated by raglib.workflow_state. Safe to rerun.",
        "BEGIN;",
        workflow_state_schema_sql(),
        workflow_init_body_sql(session_ref, definition),
        "COMMIT;",
        "",
    ]
    return "\n\n".join(statements)


def workflow_init_body_sql(
    session_ref: str | int,
    definition: dict[str, Any] | None = None,
) -> str:
    definition = definition or load_workflow_definition()
    workflow = definition["workflow"]
    steps = definition["steps"]
    name = session_name(session_ref)
    number = parse_session_number(session_ref)
    metadata = {
        "definition_format": workflow.get("definition_format"),
        "scope": workflow.get("scope"),
        "state_persistence": workflow.get("state_persistence"),
        "source_definition": str(WORKFLOW_PATH.relative_to(REPO_ROOT)),
    }

    return "\n\n".join([
        f"""
INSERT INTO session (session_number, title, notes)
VALUES ({number}, {sql_quote(f"Session {number:02d}")}, {sql_quote("Initialized by workflow state.")})
ON CONFLICT (session_number) DO NOTHING;
""".strip(),
        f"""
WITH upserted_workflow AS (
    INSERT INTO workflow_run (
        session_id, workflow_id, workflow_version, workflow_name, status, metadata
    )
    VALUES (
        (SELECT id FROM session WHERE session_number = {number}),
        {sql_quote(workflow["id"])},
        {int(workflow["version"])},
        {sql_quote(workflow.get("display_name"))},
        'initialized',
        {sql_json(metadata)}
    )
    ON CONFLICT (session_id, workflow_id, workflow_version)
    DO UPDATE SET
        workflow_name = EXCLUDED.workflow_name,
        metadata = workflow_run.metadata || EXCLUDED.metadata
    RETURNING id
)
{step_state_insert_sql(steps, name)}
""".strip(),
    ])


def step_state_insert_sql(steps: list[dict[str, Any]], name: str) -> str:
    rows = []
    for order, step in enumerate(steps, start=1):
        rows.append(
            "("
            f"{sql_quote(step['id'])}, "
            f"{order}, "
            f"{sql_quote(step['display_name'])}, "
            f"{sql_quote(step.get('lane'))}, "
            f"{sql_json(render_session_refs(step.get('expected_inputs', []), name))}, "
            f"{sql_json(render_session_refs(step.get('expected_outputs', []), name))}, "
            f"{sql_json(step.get('dependencies', []))}, "
            f"{sql_quote(step.get('gate'))}, "
            f"{sql_quote(step.get('rerun_policy'))}, "
            f"{sql_quote(step.get('canon_impact'))}, "
            f"{sql_quote(render_session_refs(step.get('command'), name))}, "
            f"{sql_json(render_session_refs(step.get('status_rules', {}), name))}, "
            f"{sql_json({'notes': step.get('notes'), 'dependency_mode': step.get('dependency_mode')})}"
            ")"
        )

    values = ",\n        ".join(rows)
    return f"""
INSERT INTO workflow_step_state (
    workflow_run_id, step_id, step_order, display_name, lane,
    inputs, outputs, dependencies, gate, rerun_policy, canon_impact,
    command, status_rules, metadata
)
SELECT
    upserted_workflow.id,
    step_values.step_id,
    step_values.step_order,
    step_values.display_name,
    step_values.lane,
    step_values.inputs,
    step_values.outputs,
    step_values.dependencies,
    step_values.gate,
    step_values.rerun_policy,
    step_values.canon_impact,
    step_values.command,
    step_values.status_rules,
    step_values.metadata
FROM upserted_workflow,
     (VALUES
        {values}
     ) AS step_values (
        step_id, step_order, display_name, lane,
        inputs, outputs, dependencies, gate, rerun_policy, canon_impact,
        command, status_rules, metadata
     )
ON CONFLICT (workflow_run_id, step_id)
DO UPDATE SET
    step_order = EXCLUDED.step_order,
    display_name = EXCLUDED.display_name,
    lane = EXCLUDED.lane,
    inputs = EXCLUDED.inputs,
    outputs = EXCLUDED.outputs,
    dependencies = EXCLUDED.dependencies,
    gate = EXCLUDED.gate,
    rerun_policy = EXCLUDED.rerun_policy,
    canon_impact = EXCLUDED.canon_impact,
    command = EXCLUDED.command,
    status_rules = EXCLUDED.status_rules,
    metadata = workflow_step_state.metadata || EXCLUDED.metadata;
""".strip()


def write_workflow_init_sql(session_ref: str | int, output_dir: Path = OUT_DIR) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    name = session_name(session_ref)
    output_path = output_dir / f"workflow_init_{name}.sql"
    output_path.write_text(initialize_workflow_sql(session_ref), encoding="utf-8")
    print(f"Wrote {output_path}")
    return output_path


def historical_workflow_seed_sql(
    start_session: int = 0,
    end_session: int = 20,
    definition: dict[str, Any] | None = None,
) -> str:
    definition = definition or load_workflow_definition()
    statements = [
        "-- Generated by raglib.workflow_state. Historical timestamps are estimated.",
        "BEGIN;",
        workflow_state_schema_sql(),
    ]
    for number in range(start_session, end_session + 1):
        statements.append(workflow_init_body_sql(number, definition))
        statements.append(historical_session_update_sql(number, definition))
    statements.extend(["COMMIT;", ""])
    return "\n\n".join(statements)


def write_historical_workflow_seed_sql(
    start_session: int = 0,
    end_session: int = 20,
    output_dir: Path = OUT_DIR,
) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / f"workflow_seed_history_session{start_session:02d}_session{end_session:02d}.sql"
    output_path.write_text(historical_workflow_seed_sql(start_session, end_session), encoding="utf-8")
    print(f"Wrote {output_path}")
    return output_path


def historical_session_update_sql(number: int, definition: dict[str, Any]) -> str:
    steps = definition["steps"]
    name = session_name(number)
    states = [historical_step_state(number, step) for step in steps]
    completed_states = [state for state in states if state["status"] in {"complete", "not_applicable"}]
    completed = len(completed_states)
    workflow_status = "completed" if completed == len(states) else "partially_completed"
    end_at = historical_session_timestamp(number)
    start_at = end_at - timedelta(minutes=max(len(states), 1) * 6)

    statements = [
        f"""
UPDATE workflow_run wr
SET
    status = {sql_quote(workflow_status)},
    initiated_at = {sql_timestamp(start_at)},
    started_at = {sql_timestamp(start_at)},
    completed_at = {sql_timestamp(end_at)},
    summary_comment = {sql_quote(f"Seeded from historical chat workflow and existing canon artifacts for {name}; timestamps are estimated.")},
    metadata = wr.metadata || {sql_json({
        "seeded_history": True,
        "timestamp_estimate": True,
        "completed_step_count": completed,
        "total_step_count": len(states),
    })}
FROM session s
WHERE wr.session_id = s.id
  AND s.session_number = {number}
  AND wr.workflow_id = {sql_quote(definition["workflow"]["id"])}
  AND wr.workflow_version = {int(definition["workflow"]["version"])};
""".strip()
    ]

    step_start = start_at
    for state in states:
        step_end = step_start + timedelta(minutes=5)
        statements.append(
            f"""
UPDATE workflow_step_state wss
SET
    status = {sql_quote(state["status"])},
    started_at = {sql_timestamp(step_start)},
    completed_at = {sql_timestamp(step_end)},
    summary_comment = {sql_quote(state["comment"])},
    metadata = wss.metadata || {sql_json({
        "seeded_history": True,
        "timestamp_estimate": True,
        "evidence": state["evidence"],
    })}
FROM workflow_run wr
JOIN session s ON s.id = wr.session_id
WHERE wss.workflow_run_id = wr.id
  AND s.session_number = {number}
  AND wr.workflow_id = {sql_quote(definition["workflow"]["id"])}
  AND wr.workflow_version = {int(definition["workflow"]["version"])}
  AND wss.step_id = {sql_quote(state["step_id"])};
""".strip()
        )
        step_start = step_start + timedelta(minutes=6)

    return "\n\n".join(statements)


def historical_step_state(number: int, step: dict[str, Any]) -> dict[str, Any]:
    name = session_name(number)
    step_id = step["id"]
    outputs = render_session_refs(step.get("expected_outputs", []), name)
    inputs = render_session_refs(step.get("expected_inputs", []), name)
    review = REPO_ROOT / "knowledge" / "Faban" / "reviews" / f"{name}_review.yaml"
    final_summary = REPO_ROOT / "knowledge" / "Faban" / "final" / f"{name}_summary.md"
    clean_summary = REPO_ROOT / "knowledge" / "Faban" / "clean" / f"{name}_summary.md"
    transcript = REPO_ROOT / "knowledge" / "Faban" / "raw" / f"{name}_transcript.txt"
    audio = REPO_ROOT / "audio" / f"{name}.wav"
    review_status = load_review_status(review)

    if step_id == "source_audio_registered":
        if audio.exists():
            return complete_state(step_id, f"Audio artifact exists for {name}.", [relative(audio)])
        return not_applicable_state(step_id, "No preserved audio recording for this historical diary-led session.", [])

    if step_id == "transcribe_audio":
        if transcript.exists():
            return complete_state(step_id, f"Transcript artifact exists for {name}.", [relative(transcript)])
        if not audio.exists():
            return not_applicable_state(step_id, "No audio transcription was needed or available for this historical diary-led session.", [])
        return pending_state(step_id, "Audio exists, but no transcript artifact was found.", [relative(audio)])

    if step_id == "diary_source_available":
        diary = REPO_ROOT / "knowledge" / "Faban" / "clean" / f"{name}_diary.md"
        if diary.exists():
            return complete_state(step_id, f"Diary source exists for {name}.", [relative(diary)])
        if transcript.exists():
            return not_applicable_state(step_id, "Transcript source exists; no diary source was found.", [relative(transcript)])
        return pending_state(step_id, "No diary or transcript source was found.", [])

    if step_id == "source_status_check":
        if transcript.exists() or (REPO_ROOT / "knowledge" / "Faban" / "clean" / f"{name}_diary.md").exists():
            return complete_state(step_id, "At least one source artifact exists and was used for historical review.", existing_paths(inputs))
        return pending_state(step_id, "No usable source artifact was found.", [])

    if step_id in {
        "extract_events",
        "filter_events",
        "classify_events",
        "normalize_events",
        "merge_events",
        "validate_draft",
        "postextract_shortcut",
    }:
        found_outputs = existing_paths(outputs)
        if found_outputs and len(found_outputs) == count_file_outputs(outputs):
            return complete_state(step_id, f"Draft artifact outputs exist for {name}.", found_outputs)
        if clean_summary.exists() and review.exists():
            return not_applicable_state(
                step_id,
                "Historical session was reviewed from diary/source summary before this draft pipeline stage was fully preserved.",
                [relative(clean_summary), relative(review)],
            )
        return pending_state(step_id, "Expected draft artifacts were not found.", found_outputs)

    if step_id == "summarize_draft":
        if clean_summary.exists():
            return complete_state(step_id, f"Draft/source summary exists for {name}.", [relative(clean_summary)])
        return pending_state(step_id, "No draft/source summary was found.", [])

    if step_id == "initialize_review":
        if review.exists():
            return complete_state(step_id, f"Human review file exists for {name}.", [relative(review)])
        return pending_state(step_id, "No review file was found.", [])

    if step_id in {"edit_review_decisions", "mark_reviewed"}:
        if review_status in {"reviewed", "applied"}:
            return complete_state(step_id, f"Review status is {review_status}.", [relative(review)])
        return pending_state(step_id, f"Review status is {review_status or 'missing'}.", existing_paths([str(review)]))

    if step_id == "apply_review":
        if review_status == "applied":
            return complete_state(step_id, "Review has been applied to canon/database workflow.", [relative(review)])
        return pending_state(step_id, f"Review status is {review_status or 'missing'}, not applied.", existing_paths([str(review)]))

    if step_id == "write_final_summary":
        if final_summary.exists():
            return complete_state(step_id, f"Final canonical summary exists for {name}.", [relative(final_summary)])
        return pending_state(step_id, "No final canonical summary was found.", [])

    if step_id == "update_lore_sections":
        if final_summary.exists():
            return complete_state(step_id, "Cross-session lore and registry implications were handled during historical canon passes where applicable.", [relative(final_summary)])
        return pending_state(step_id, "Final summary missing, so lore follow-up cannot be confirmed.", [])

    if step_id in {"dbload_refresh", "run_health", "run_tests", "web_smoke_check"}:
        if final_summary.exists() and review_status == "applied":
            return complete_state(step_id, "Covered by campaign-wide verification passes after historical review and canon loading.", [relative(final_summary), relative(review)])
        return pending_state(step_id, "Historical verification cannot be confirmed because reviewed canon is incomplete.", existing_paths([str(final_summary), str(review)]))

    if step_id in {"version_revision_update", "git_commit", "git_tag", "git_push"}:
        if final_summary.exists() and review_status == "applied":
            return complete_state(step_id, "Captured in project version-control history after the historical review work.", [relative(final_summary), relative(review)])
        return pending_state(step_id, "Version-control closure cannot be confirmed because reviewed canon is incomplete.", existing_paths([str(final_summary), str(review)]))

    found = existing_paths(outputs)
    if found:
        return complete_state(step_id, f"Expected output artifact exists for {name}.", found)
    return pending_state(step_id, "No historical evidence found for this step.", [])


def complete_state(step_id: str, comment: str, evidence: list[str]) -> dict[str, Any]:
    return {"step_id": step_id, "status": "complete", "comment": comment, "evidence": evidence}


def not_applicable_state(step_id: str, comment: str, evidence: list[str]) -> dict[str, Any]:
    return {"step_id": step_id, "status": "not_applicable", "comment": comment, "evidence": evidence}


def pending_state(step_id: str, comment: str, evidence: list[str]) -> dict[str, Any]:
    return {"step_id": step_id, "status": "pending", "comment": comment, "evidence": evidence}


def historical_session_timestamp(number: int) -> datetime:
    name = session_name(number)
    paths = [
        f"knowledge/Faban/reviews/{name}_review.yaml",
        f"knowledge/Faban/final/{name}_summary.md",
        f"knowledge/Faban/clean/{name}_summary.md",
    ]
    result = subprocess.run(
        ["git", "log", "-1", "--format=%cI", "--", *paths],
        cwd=REPO_ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    value = result.stdout.strip().splitlines()
    if value:
        return datetime.fromisoformat(value[0])
    return datetime(2026, 5, 5, 12, 0, tzinfo=timezone.utc)


def load_review_status(path: Path) -> str | None:
    if not path.exists():
        return None
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return data.get("status") if isinstance(data, dict) else None


def existing_paths(paths: list[Any]) -> list[str]:
    found = []
    for item in paths:
        if not isinstance(item, str) or any(token in item for token in ["operator ", "database ", "reviewed ", "source artifacts"]):
            continue
        matches = list(REPO_ROOT.glob(item)) if "*" in item else [REPO_ROOT / item]
        found.extend(relative(path) for path in matches if path.exists())
    return sorted(set(found))


def count_file_outputs(paths: list[Any]) -> int:
    return len([
        item for item in paths
        if isinstance(item, str) and not any(token in item for token in ["operator ", "database ", "reviewed ", "source artifacts"])
    ])


def relative(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def render_session_refs(value: Any, name: str) -> Any:
    if isinstance(value, str):
        return value.replace("sessionXX", name)
    if isinstance(value, list):
        return [render_session_refs(item, name) for item in value]
    if isinstance(value, dict):
        return {key: render_session_refs(item, name) for key, item in value.items()}
    return value


def sql_quote(value: Any) -> str:
    if value is None:
        return "NULL"
    return "'" + str(value).replace("'", "''") + "'"


def sql_json(value: Any) -> str:
    return f"{sql_quote(json.dumps(value, sort_keys=True))}::jsonb"


def sql_timestamp(value: datetime) -> str:
    return f"TIMESTAMPTZ {sql_quote(value.isoformat())}"
