import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from raglib.config import BASE2
from scripts.load_summaries import (
    OUT_DIR,
    SONG_PROMPTS_PATH,
    SONG_TITLES,
    parse_song_prompts,
    song_prompt_sql,
    song_schema_sql,
    sql_quote,
)


OUT_SQL = BASE2 / "farrlind" / "out" / "load_songbook.sql"
OUT_REPORT = BASE2 / "farrlind" / "out" / "load_songbook_report.md"


def songbook_pipeline_run_sql(prompt_count: int, report_path: Path) -> str:
    return f"""
INSERT INTO pipeline_run (
    pipeline_stage, model_used, input_file, output_file,
    records_created, records_updated, success
)
VALUES (
    'songbook_db_load',
    'deterministic-python',
    {sql_quote(str(SONG_PROMPTS_PATH))},
    {sql_quote(str(report_path))},
    0,
    {prompt_count},
    TRUE
);
""".strip()


def build_songbook_sql(prompts: list[dict], report_path: Path) -> str:
    statements = [
        "-- Generated by scripts/load_songbook.py. Safe to rerun.",
        "BEGIN;",
        song_schema_sql(),
    ]
    statements.extend(song_prompt_sql(prompt) for prompt in prompts)
    statements.append(songbook_pipeline_run_sql(len(prompts), report_path))
    statements.append("COMMIT;")
    statements.append("")
    return "\n\n".join(statements)


def write_report(prompts: list[dict], warnings: list[str], report_path: Path) -> Path:
    loaded_numbers = {prompt["song_number"] for prompt in prompts}
    missing = [
        (number, title)
        for number, title in SONG_TITLES.items()
        if number not in loaded_numbers
    ]
    with_tempo = [prompt for prompt in prompts if prompt.get("tempo")]
    with_meter = [prompt for prompt in prompts if prompt.get("meter")]
    with_key = [prompt for prompt in prompts if prompt.get("key")]
    with_instrumentation = [prompt for prompt in prompts if prompt.get("instrumentation")]

    lines = [
        "# Songbook Load Report",
        "",
        f"Source: `{SONG_PROMPTS_PATH}`",
        f"SQL: `{OUT_SQL}`",
        "",
        "## Summary",
        "",
        f"- Songs in index: {len(SONG_TITLES)}",
        f"- Complete prompts loaded: {len(prompts)}",
        f"- Missing or skipped prompts: {len(missing)}",
        f"- Tempo values: {len(with_tempo)}",
        f"- Meter values: {len(with_meter)}",
        f"- Key values: {len(with_key)}",
        f"- Instrumentation values: {len(with_instrumentation)}",
        "",
        "## Loaded Songs",
        "",
    ]

    for prompt in prompts:
        fields = []
        if prompt.get("tempo"):
            fields.append("tempo")
        if prompt.get("meter"):
            fields.append("meter")
        if prompt.get("key"):
            fields.append("key")
        if prompt.get("instrumentation"):
            fields.append("instrumentation")
        field_text = ", ".join(fields) if fields else "prompt only"
        canonical_title = SONG_TITLES.get(prompt["song_number"], prompt["title"])
        lines.append(f"- {prompt['song_number']:02d}. {canonical_title} ({field_text})")

    lines.extend(["", "## Missing Or Skipped", ""])
    for number, title in missing:
        lines.append(f"- {number:02d}. {title}")

    if warnings:
        lines.extend(["", "## Warnings", ""])
        lines.extend(f"- {warning}" for warning in warnings)

    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return report_path


def write_songbook_sql() -> tuple[Path, Path, list[dict], list[str]]:
    prompts, warnings = parse_song_prompts()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_SQL.write_text(build_songbook_sql(prompts, OUT_REPORT), encoding="utf-8")
    write_report(prompts, warnings, OUT_REPORT)

    print(f"Wrote {OUT_SQL}")
    print(f"Wrote {OUT_REPORT}")
    print(f"Song prompts: {len(prompts)}")
    print(f"Missing or skipped: {len(SONG_TITLES) - len({prompt['song_number'] for prompt in prompts})}")
    for warning in warnings:
        print(f"Song prompt warning: {warning}")
    return OUT_SQL, OUT_REPORT, prompts, warnings


def apply_sql(sql_path: Path, container: str, user: str, database: str):
    target = f"/tmp/{sql_path.name}"
    subprocess.run(["docker", "cp", str(sql_path), f"{container}:{target}"], check=True)
    subprocess.run(
        ["docker", "exec", container, "psql", "-v", "ON_ERROR_STOP=1", "-U", user, "-d", database, "-f", target],
        check=True,
    )


def parse_args():
    parser = argparse.ArgumentParser(description="Load curated Faban songbook metadata into Postgres.")
    parser.add_argument("--apply", action="store_true", help="Apply generated SQL through Docker.")
    parser.add_argument("--container", default="farrlind_db")
    parser.add_argument("--user", default="admin")
    parser.add_argument("--database", default="farrlind")
    return parser.parse_args()


def main():
    args = parse_args()
    sql_path, _report_path, _prompts, _warnings = write_songbook_sql()

    if args.apply:
        apply_sql(sql_path, args.container, args.user, args.database)


if __name__ == "__main__":
    main()
